name: deploy-master
on:
  push:
    branches: ['master']

jobs:
  deploy:
    name: Deploy to MASTER
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    name: checkout
    
    - name: executing remote ssh commands using ssh key
    uses: appleboy/ssh-action@master
    with:	
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: sh test-live.sh
