name: UAT Auto-PR
on:
  push:
    branches: ['dev']

jobs:
  pull-request:
    name: Open PR to uat
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "uat"
        pr_title: "Pulling ${{ github.ref }} into uat"
        pr_body: "👑 *An automated PR*"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
