name: uat-pr-master
on:
  push:
    branches: ['uat']

jobs:
  pull-request:
    name: Open PR to MASTER
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - uses: repo-sync/pull-request@v2    
      name: pull-request
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: "👑 *An automated PR*"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Assign Reviewers to PR"
      uses: itsOliverBott/assign-pr-reviewers@release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        users: "safichoudhury,skmujahed" # comma-separated (example: "itsOliverBott, SantaClaus, b4tman, sp0derman")
        ignore-drafts: true # defaults to false if not provided

